<!DOCTYPE html>
< html lang="en">

    <HEAD>
     <meta charset="UTF-8">
     <title>Formulario</title>
      </head>

<body>

<form action="" name="formulario" method="get">

<!-- Explicar Require -->

<input type="text" name="Correo" id="Correo" maxlength="30" placeholder="Correo: <br>
<input type="text" name="Contraseña" id="Contraseña" maxlength="25" placeholder="Contraseña: <br>
<input type="submit" id="btn" name="btn" value="Iniciar seseion">

</form>
</head>

<body>

<form action="contacto.html" name="formulario" method="get">

</form I

<script>

(function(){

}()

</script>

</body>

</html>